[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# library crate
rand = "0.8.3" #Only downloads dependencies from 0.8.3 - 9.0.0